// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSe0fDvJhjzX-BQzaTyppZoRiZ03Kf9JQ',
    appId: '1:17025094425:web:87e9c3cf0aaf0c4a3f6b88',
    messagingSenderId: '17025094425',
    projectId: 'carenta-auth',
    authDomain: 'carenta-auth.firebaseapp.com',
    storageBucket: 'carenta-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimYn4FWCBrqRm5NpUOMIPaNMg0uObCAA',
    appId: '1:17025094425:android:c58a0e5ea50e518c3f6b88',
    messagingSenderId: '17025094425',
    projectId: 'carenta-auth',
    storageBucket: 'carenta-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsJtzw8jkuGco2FVLEbMnLwXJq85__pL4',
    appId: '1:17025094425:ios:98b1d13e007251483f6b88',
    messagingSenderId: '17025094425',
    projectId: 'carenta-auth',
    storageBucket: 'carenta-auth.firebasestorage.app',
    iosBundleId: 'com.example.carenta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsJtzw8jkuGco2FVLEbMnLwXJq85__pL4',
    appId: '1:17025094425:ios:98b1d13e007251483f6b88',
    messagingSenderId: '17025094425',
    projectId: 'carenta-auth',
    storageBucket: 'carenta-auth.firebasestorage.app',
    iosBundleId: 'com.example.carenta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSe0fDvJhjzX-BQzaTyppZoRiZ03Kf9JQ',
    appId: '1:17025094425:web:f8dc35fa31e000343f6b88',
    messagingSenderId: '17025094425',
    projectId: 'carenta-auth',
    authDomain: 'carenta-auth.firebaseapp.com',
    storageBucket: 'carenta-auth.firebasestorage.app',
  );
}
